vim.opt.autoindent = true
vim.opt.backup = false
vim.opt.colorcolumn = "80"
--vim.opt.columns = 80		--dont know what this does
--vim.opt.completeopt = { " menuone", "noselect" }
vim.opt.copyindent = true
--vim.opt.cursorcolumn = true
vim.opt.cursorline = true	--adds highlight to current line
vim.opt.clipboard = "unnamedplus"
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.mouse = "a"
vim.opt.relativenumber = true;
vim.opt.number = true;
vim.opt.scrolloff = 8
vim.opt.shiftwidth = 4
vim.opt.showmode = false
vim.opt.showtabline = 2		--shows tab at top of screen, questionable
vim.opt.signcolumn = "yes"	--adds coloumn to left of screen, for errors
vim.opt.smartindent = true
vim.opt.smartcase = true
--vim.opt.softtabstop = 0
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.statusline = ""		--TODO
vim.opt.swapfile = false
vim.opt.termguicolors = true
vim.opt.wrap = false
